trigger:
  branches:
    include:
      - develop
      - release
      - main

resources:
- repo: self

variables:
  - group: general-pipeline

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    - group: loccitane-vdgo-front-dev
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - group: loccitane-vdgo-front-prd

stages:
- stage: CI
  displayName: 'Next.js building'
  jobs:
  - job: Build
    displayName: 'Build and Package FRONT'
    pool:
      vmImage: $(poolVmImage)
    condition: |
      or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
         eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - template: azure-pipelines-templates/front-build.yml


- stage: CD
  displayName: "Deploy to Kubernetes"
  dependsOn: CI
  jobs:
  - job: Deploy
    displayName: "Deploy FRONT"
    pool:
      vmImage: $(poolVmImage)
    condition: |
      or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
         eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - template: azure-pipelines-templates/front-deploy.yml