import '@/styles/drupal/drupalGlobals.css';
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { GoogleTagManager } from '@next/third-parties/google'
import "./globals.css";
import { AppProvider } from "@/contexts/app.context";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

const ralewayfont = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const loccitaneSans = Raleway({
  variable: "--font-loccitane-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_BR">
      <head></head>
      <body
        //data-teste={process.env.NEXT_API_BASE_URL}
        data-teste={process.env.NEXT_PUBLIC_API_BASE_URL} // Alterado para NEXT_PUBLIC_
        className={`${ralewayfont.className} ${ralewayfont.variable} ${loccitaneSans.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <AppProvider>
            {children}
          </AppProvider>
        </AppRouterCacheProvider>
        {/* Google Tag Manager */}
        {process.env.NEXT_PUBLIC_GTM_CODE && (
          <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_CODE} />
        )}
      </body>
      {/* <GoogleTagManager gtmId={process.env.NEXT_GTM_CODE || ''} /> */}
    </html>
  );
}
