import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { GoogleTagManager } from '@next/third-parties/google'
import "./globals.css";
import { AppProvider } from "@/contexts/app.context";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

const ralewayfont = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const loccitaneSans = Raleway({
  variable: "--font-loccitane-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_BR">
      <head>
      <link rel="stylesheet" href={`${process.env.NEXT_PUBLIC_DRUPAL_BASE_URL}modules/custom/custom_ckeditor_styles/css/editor-styles.css`} />
        <meta
          httpEquiv="Content-Security-Policy"
          content="
              script-src 'self' 'unsafe-eval' *.googleapis.com *.acesso.io *.unico.run *.unico.io *.unico.app; 
              worker-src 'self' blob:; 
              child-src 'self' blob:;
              style-src 'self' 'unsafe-inline' *.googleapis.com *.acesso.io *.unico.run *.unico.io *.unico.app vdgo-cms-dev.squadra.com.br;
              font-src 'self' data: https://fonts.gstatic.com *.acesso.io *.unico.run *.unico.io *.unico.app;
              img-src 'self' data: blob: *.acesso.io *.unico.run *.unico.io *.unico.app vdgo-cms-dev.squadra.com.br;
              media-src 'self' data: *.acesso.io *.unico.run *.unico.io *.unico.app vdgo-cms-dev.squadra.com.br;
              script-src-elem 'self' 'unsafe-inline' blob: *.googleapis.com *.acesso.io *.unico.run *.unico.io *.unico.app"
        />
      </head>
      <body
        className={`${ralewayfont.className} ${ralewayfont.variable} ${loccitaneSans.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <AppProvider>
            {children}
          </AppProvider>
        </AppRouterCacheProvider>
        {/* Google Tag Manager */}
        {process.env.NEXT_PUBLIC_GTM_CODE && (
          <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_CODE} />
        )}
      </body>
    </html>
  );
}
