apiVersion: v1
kind: Secret
metadata:
  name: secrets-environment-{{ include "loccitane-vdgo-front.fullname" . }}
data:
  TZ: {{ .Values.env.TZ |toString | b64enc }}
  NEXT_PUBLIC_DRUPAL_BASE_URL: {{ .Values.env.NEXT_PUBLIC_DRUPAL_BASE_URL |toString | b64enc }}
  NEXT_IMAGE_DOMAIN: {{ .Values.env.NEXT_IMAGE_DOMAIN |toString | b64enc }}
  NEXT_GTM_CODE: {{ .Values.env.NEXT_GTM_CODE |toString | b64enc }}
  NEXT_API_BASE_URL: {{ .Values.env.NEXT_API_BASE_URL |toString | b64enc }}
  NEXT_CREDILINK_UNICO_HOSTNAME: {{ .Values.env.NEXT_CREDILINK_UNICO_HOSTNAME |toString | b64enc }}
  NEXT_CREDILINK_UNICO_HOSTKEY: {{ .Values.env.NEXT_CREDILINK_UNICO_HOSTKEY |toString | b64enc }}
  NEXT_ALLOWED_DOMAINS_SOURCE: {{ .Values.env.NEXT_ALLOWED_DOMAINS_SOURCE |toString | b64enc }}
  NEXT_LINK_PORTAL_TSHIELD: {{ .Values.env.NEXT_LINK_PORTAL_TSHIELD |toString | b64enc }}
